name: Periodic health check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # Runs every day at 8:00 AM UTC

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check deployed application
        uses: Jtalk/url-health-check-action@v5
        with:
          url: https://fs-pokedex-ci-cd-l0fl.onrender.com
          max-attempts: 3
          retry-delay: 5s