name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run build

  deploy:
    needs: [build_and_test]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl --fail ${{ secrets.RENDER_DEPLOY_HOOK }}

  notify_success:
    needs: [deploy]
    if: ${{ needs.deploy.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify success in Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: Success
          title: "✅ Deployment Successful!"
          description: |
            Deployment Details

            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
          nodetail: true

  notify_failure:
    needs: [build_and_test, deploy]
    if: ${{ failure() && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure in Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: Failure
          title: "❌ Build or deployment failed!"
          description: |
            **Failure Details**

            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            **Workflow:** ${{ github.workflow }}
            **Failed job(s):** build_and_test=${{ needs.build_and_test.result }}, deploy=${{ needs.deploy.result }}

            **View Commit:** ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
            **View Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          nodetail: true

  tag_release:
    needs: [deploy]
    if: ${{ needs.deploy.result == 'success' && github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
